version: '3'
services:
        mica:
                build: .
                ports:
                        - "8872:8082"
                        - "8835:8445"
                environment:
                        - MICA_ADMINISTRATOR_PASSWORD=password
                        - MICA_ANONYMOUS_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - OPAL_HOST=opal
                        - OPAL_PORT=8443
                        - AGATE_HOST=agate
                        - AGATE_PORT=8444
                volumes:
                        - config_mica:/srv
        mongo:
                image: mongo
                volumes:
                        - mongodb:/data/db
        opal:
                image: obiba/opal:latest
                ports:
                        - "8833:8443"
                        - "8870:8080"
                environment:
                        - OPAL_ADMINISTRATOR_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - AGATE_HOST=agate
                        - AGATE_PORT=8444
                volumes:
                        - config_opal:/srv
        agate:
                image: obiba/agate:latest
                ports:
                        - "8834:8444"
                        - "8871:8081"
                environment:
                        - AGATE_ADMINISTRATOR_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - RECAPTCHA_SITE_KEY=6Lfo7gYTAAAAAOyl8_MHuH-AVBzRDtpIuJrjL3Pb
                        - RECAPTCHA_SECRET_KEY=6Lfo7gYTAAAAADym-vSDvPBeBCXaxIprA0QXLk_b
                volumes:
                        - config_agate:/srv

volumes:
        mongodb: null
        config_mica: null
        config_agate: null
        config_opal: null
