---
title: "Validators"
output:
  knitrBootstrap::bootstrap_document:
    menu: FALSE
    theme: Flatly
  df_print: kable

params:
  date: !r format(Sys.time(), '%B %d, %Y')
  time: !r format(Sys.time(), '%H:%m:%S')
---

<p class="text-muted">
  <small>
    Report generated by [Opal Analysis Validate](https://github.com/obiba/opal-analysis-validate) plugin on `r params$date` at `r params$time`
  </small>
</p>

```{r setup, include=FALSE}
library(knitr)
library(knitrBootstrap)
```

``` {r message=FALSE, echo=FALSE}
source("routine.R")
```

# Overview

Analysis routine ``r metadata$name`` was executed on table ``r metadata$table`` in project ``r metadata$datasource`` on `r metadata$variableInfo`.

# Results

## Summary Barplot {data-icon="fa-signal"}

``` {r echo=FALSE, bootstrap.thumbnail.size="col-xs-12", fig.width=12}
barplot(summaryData[["confront"]], main="")
```

## Summary Table

``` {r echo=FALSE}
kable(summaryData[["summary"]])
```

## Errors

``` {r echo=FALSE, results="asis"}
if (length(errorList) > 0) {
  gsub("\\|x", "|", kable(unlist(errorList)))
} else {
  gsub("\\|x", "|", kable(c("No errors found.")))
}
```
